server:
  port: 8081
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.8.156:3306/jdbc
    driver-class-name: com.mysql.jdbc.Driver
    schema:
      - classpath:department.sql
#person:
#  name: MysteryGuest
#  age: 21
#  birth: 1999/01/09
#  map: {k1: v1, k2: v2}
#  list:
#    - China
#    - Hubei
#  pet:
#    name: niuniu
#    age: 5
#spring:
#  profiles:
#    active: dev
---
server:
  port: 8084
spring:
  profiles: dev
---
server:
  port: 8085
  spring:
    profiles: prod