server:
  port: 8081
spring:
  # 数据源基本配置
  datasource:
    # 与DataSourceProperties.class下的属性一一对应
    username: root
    password: Bestwich1314
#    url: jdbc:mysql://192.168.6.33:3306/jdbc
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
#    schema:
#      - classpath:department.sql
    #############################################
    #######   Druid configuration start   #######
    #############################################
    # 数据源其他配置, 底部这种颜色是因为DataSourceProperties.class下没有这些属性, 并不能绑定到数据库的配置里
    # 但DruidDataSource.java中有这些属性
    # 想要生效, 自己配置, config.DruidConfig
#    initialSize: 5
#    minIdle: 5
#    maxActive: 20
#    maxWait: 60000
#    timeBetweenEvictionRunsMillis: 60000
#    minEvictableIdleTimeMillis: 300000
#    validationQuery: SELECT 1 FROM DUAL
#    testWhileIdle: true
#    testOnBorrow: false
#    testOnReturn: false
#    poolPreparedStatements: true
    #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
#    filters: stat,wall,log4j
#    maxPoolPreparedStatementPerConnectionSize: 20
#    useGlobalDataSourceStat: true
#    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
    #############################################
    #######   Druid configuration end   #######
    #############################################

    #############################################
    #######    JPA configuration start    #######
    #############################################
#  jpa:
#    hibernate:
      # 更新或者创建数据表结构
#      ddl-auto: update
      # 控制台显示SQL
#    show-sql: true
    #############################################
    #######     JPA configuration end     #######
    #############################################

#    第一次启动后就可以注释掉, 以防下次启动还会执行
#    schema:
#      - classpath:sql/department.sql
#      - classpath:sql/employee.sql

#person:
#  name: MysteryGuest
#  age: 21
#  birth: 1999/01/09
#  map: {k1: v1, k2: v2}
#  list:
#    - China
#    - Hubei
#  pet:
#    name: niuniu
#    age: 5
#spring:
#  profiles:
#    active: dev
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
---
server:
  port: 8084
spring:
  profiles: dev
---
server:
  port: 8085
  spring:
    profiles: prod