server:
  port: 8081
#person:
#  name: MysteryGuest
#  age: 21
#  birth: 1999/01/09
#  map: {k1: v1, k2: v2}
#  list:
#    - China
#    - Hubei
#  pet:
#    name: niuniu
#    age: 5
spring:
  profiles:
    active: dev
---
server:
  port: 8084
spring:
  profiles: dev
---
server:
  port: 8085
  spring:
    profiles: prod